SELECT 
    COURSE_NAME, 
    COUNT(*) AS cnt
FROM (
    SELECT 
        c.COURSE_NAME, 
        s.STUDENT_POPULATION_CODE_REF
    FROM 
        ATTENDANCE att
    JOIN 
        COURSES c ON c.COURSE_CODE = att.ATTENDANCE_COURSE_REF
    JOIN 
        STUDENTS s ON att.ATTENDANCE_STUDENT_REF = s.STUDENT_EPITA_EMAIL
    WHERE 
        s.STUDENT_POPULATION_CODE_REF = %s
        AND s.STUDENT_POPULATION_YEAR_REF = %s
        AND s.STUDENT_POPULATION_PERIOD_REF = %s
    GROUP BY 
        att.ATTENDANCE_STUDENT_REF, 
        c.COURSE_NAME, 
        s.STUDENT_POPULATION_CODE_REF
) sub
GROUP BY COURSE_NAME
